### ISSUE TITLE
pdf reader issue

### ISSUE THREAD

**Issue by ilLeoo** [Odinmylord/Transpiler-ASD-UniTN#2]
"ModuleNotFoundError: No module named 'pdf_reader'" when i run the script

**Comment by odinmylord** [comment]
I just realized that when I made the commit I forgot to add the pdf_reader module. Will fix as soon as possible. Sorry for the inconvenience

**Comment by odinmylord** [comment]
Added the file "pdf_reader.py", now it should work fine. Thank you for opening the issue
